-- Quail Dashboard Cortex Search Services Creation Script
-- This script creates Cortex Search Services for all VARCHAR dimensions in the QUANTIUM_HEALTHCARE_DEMO schema
-- Generated for healthcare analytics with Snowflake Intelligence

-- Set context
USE DATABASE QUANTIUM_HEALTHCARE_DEMO;
USE SCHEMA QUANTIUM_HEALTHCARE_DEMO;

-- DIM_ATC_HIERARCHY Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_CODE
ON ATC_CODE
ATTRIBUTES ATC_CODE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_CODE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_CODE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_DESCRIPTION
ON ATC_DESCRIPTION
ATTRIBUTES ATC_DESCRIPTION
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_DESCRIPTION
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_DESCRIPTION IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_1
ON ATC_LEVEL_DESC_1
ATTRIBUTES ATC_LEVEL_DESC_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_LEVEL_DESC_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_2
ON ATC_LEVEL_DESC_2
ATTRIBUTES ATC_LEVEL_DESC_2
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_2
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_LEVEL_DESC_2 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_3
ON ATC_LEVEL_DESC_3
ATTRIBUTES ATC_LEVEL_DESC_3
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_3
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_LEVEL_DESC_3 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_4
ON ATC_LEVEL_DESC_4
ATTRIBUTES ATC_LEVEL_DESC_4
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_4
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_LEVEL_DESC_4 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_5
ON ATC_LEVEL_DESC_5
ATTRIBUTES ATC_LEVEL_DESC_5
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_5
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_ATC_HIERARCHY"
    WHERE ATC_LEVEL_DESC_5 IS NOT NULL
);

-- DIM_GEOGRAPHY Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_GEOGRAPHY_PROVINCE
ON PROVINCE
ATTRIBUTES PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_GEOGRAPHY"
    WHERE PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_GEOGRAPHY_REGION
ON REGION
ATTRIBUTES REGION
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REGION
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_GEOGRAPHY"
    WHERE REGION IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_GEOGRAPHY_COUNTRY
ON COUNTRY
ATTRIBUTES COUNTRY
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT COUNTRY
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_GEOGRAPHY"
    WHERE COUNTRY IS NOT NULL
);

-- DIM_MEDICAL_SCHEMES Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_MEDICAL_SCHEMES_SCHEME_NAME
ON SCHEME_NAME
ATTRIBUTES SCHEME_NAME
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SCHEME_NAME
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_MEDICAL_SCHEMES"
    WHERE SCHEME_NAME IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_MEDICAL_SCHEMES_PLAN_GROUP
ON PLAN_GROUP
ATTRIBUTES PLAN_GROUP
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PLAN_GROUP
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_MEDICAL_SCHEMES"
    WHERE PLAN_GROUP IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_MEDICAL_SCHEMES_PLAN_TYPE
ON PLAN_TYPE
ATTRIBUTES PLAN_TYPE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PLAN_TYPE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_MEDICAL_SCHEMES"
    WHERE PLAN_TYPE IS NOT NULL
);

-- DIM_PATIENTS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PATIENTS_ENTITY_NO
ON ENTITY_NO
ATTRIBUTES ENTITY_NO
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENTITY_NO
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PATIENTS"
    WHERE ENTITY_NO IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PATIENTS_AGE_BUCKET
ON AGE_BUCKET
ATTRIBUTES AGE_BUCKET
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT AGE_BUCKET
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PATIENTS"
    WHERE AGE_BUCKET IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PATIENTS_AGE_GROUPS
ON AGE_GROUPS
ATTRIBUTES AGE_GROUPS
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT AGE_GROUPS
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PATIENTS"
    WHERE AGE_GROUPS IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PATIENTS_GENDER
ON GENDER
ATTRIBUTES GENDER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT GENDER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PATIENTS"
    WHERE GENDER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PATIENTS_PROVINCE
ON PROVINCE
ATTRIBUTES PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PATIENTS"
    WHERE PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PATIENTS_REGION_OF_RESIDENCE
ON REGION_OF_RESIDENCE
ATTRIBUTES REGION_OF_RESIDENCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REGION_OF_RESIDENCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PATIENTS"
    WHERE REGION_OF_RESIDENCE IS NOT NULL
);

-- DIM_PHARMACEUTICALS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PHARMACEUTICALS_PRODUCT_NAME
ON PRODUCT_NAME
ATTRIBUTES PRODUCT_NAME
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PRODUCT_NAME
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PHARMACEUTICALS"
    WHERE PRODUCT_NAME IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PHARMACEUTICALS_NAPPI_MANUFACTURER
ON NAPPI_MANUFACTURER
ATTRIBUTES NAPPI_MANUFACTURER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT NAPPI_MANUFACTURER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PHARMACEUTICALS"
    WHERE NAPPI_MANUFACTURER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PHARMACEUTICALS_STRENGTH
ON STRENGTH
ATTRIBUTES STRENGTH
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STRENGTH
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PHARMACEUTICALS"
    WHERE STRENGTH IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PHARMACEUTICALS_DOSAGE_FORM
ON DOSAGE_FORM
ATTRIBUTES DOSAGE_FORM
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DOSAGE_FORM
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PHARMACEUTICALS"
    WHERE DOSAGE_FORM IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PHARMACEUTICALS_ATC_CODE
ON ATC_CODE
ATTRIBUTES ATC_CODE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_CODE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PHARMACEUTICALS"
    WHERE ATC_CODE IS NOT NULL
);

-- DIM_PRODUCTS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_MANUFACTURER
ON MANUFACTURER
ATTRIBUTES MANUFACTURER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MANUFACTURER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE MANUFACTURER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_HIGH_LEVEL_1
ON HIGH_LEVEL_1
ATTRIBUTES HIGH_LEVEL_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE HIGH_LEVEL_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_HIGH_LEVEL_2
ON HIGH_LEVEL_2
ATTRIBUTES HIGH_LEVEL_2
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_2
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE HIGH_LEVEL_2 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_HIGH_LEVEL_3
ON HIGH_LEVEL_3
ATTRIBUTES HIGH_LEVEL_3
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_3
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE HIGH_LEVEL_3 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_HIGH_LEVEL_4
ON HIGH_LEVEL_4
ATTRIBUTES HIGH_LEVEL_4
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_4
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE HIGH_LEVEL_4 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_TR_LEVEL_1
ON TR_LEVEL_1
ATTRIBUTES TR_LEVEL_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TR_LEVEL_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE TR_LEVEL_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_LEVELS_CONCAT_TILL_2
ON LEVELS_CONCAT_TILL_2
ATTRIBUTES LEVELS_CONCAT_TILL_2
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT LEVELS_CONCAT_TILL_2
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE LEVELS_CONCAT_TILL_2 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_ALL_LEVELS_CONCAT
ON ALL_LEVELS_CONCAT
ATTRIBUTES ALL_LEVELS_CONCAT
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ALL_LEVELS_CONCAT
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE ALL_LEVELS_CONCAT IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PRODUCTS_ALL_LEVELS_CONCAT_4
ON ALL_LEVELS_CONCAT_4
ATTRIBUTES ALL_LEVELS_CONCAT_4
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ALL_LEVELS_CONCAT_4
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PRODUCTS"
    WHERE ALL_LEVELS_CONCAT_4 IS NOT NULL
);

-- DIM_PROVIDERS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PROVIDERS_PROVIDER_NAME
ON PROVIDER_NAME
ATTRIBUTES PROVIDER_NAME
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_NAME
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PROVIDERS"
    WHERE PROVIDER_NAME IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PROVIDERS_PROVIDER_GROUP
ON PROVIDER_GROUP
ATTRIBUTES PROVIDER_GROUP
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_GROUP
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PROVIDERS"
    WHERE PROVIDER_GROUP IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PROVIDERS_PROVIDER_CATEGORY
ON PROVIDER_CATEGORY
ATTRIBUTES PROVIDER_CATEGORY
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_CATEGORY
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PROVIDERS"
    WHERE PROVIDER_CATEGORY IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PROVIDERS_PROVIDER_TYPE
ON PROVIDER_TYPE
ATTRIBUTES PROVIDER_TYPE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_TYPE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PROVIDERS"
    WHERE PROVIDER_TYPE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PROVIDERS_PROVINCE
ON PROVINCE
ATTRIBUTES PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PROVIDERS"
    WHERE PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_DIM_PROVIDERS_REGION
ON REGION
ATTRIBUTES REGION
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REGION
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."DIM_PROVIDERS"
    WHERE REGION IS NOT NULL
);

-- HEALTHCARE_CLAIMS Dimension Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_MANUFACTURER
ON MANUFACTURER
ATTRIBUTES MANUFACTURER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MANUFACTURER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE MANUFACTURER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_PRACTICE_NO_DESCR
ON PRACTICE_NO_DESCR
ATTRIBUTES PRACTICE_NO_DESCR
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PRACTICE_NO_DESCR
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE PRACTICE_NO_DESCR IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_CATEGORY_DESCR
ON CATEGORY_DESCR
ATTRIBUTES CATEGORY_DESCR
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CATEGORY_DESCR
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE CATEGORY_DESCR IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_PROVIDER_GROUP
ON PROVIDER_GROUP
ATTRIBUTES PROVIDER_GROUP
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_GROUP
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE PROVIDER_GROUP IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_P_PROVINCE
ON P_PROVINCE
ATTRIBUTES P_PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT P_PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE P_PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_PROVINCE_DESCR
ON PROVINCE_DESCR
ATTRIBUTES PROVINCE_DESCR
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE_DESCR
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE PROVINCE_DESCR IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_HIGH_LEVEL_1
ON HIGH_LEVEL_1
ATTRIBUTES HIGH_LEVEL_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE HIGH_LEVEL_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_HIGH_LEVEL_2
ON HIGH_LEVEL_2
ATTRIBUTES HIGH_LEVEL_2
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_2
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE HIGH_LEVEL_2 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_HIGH_LEVEL_3
ON HIGH_LEVEL_3
ATTRIBUTES HIGH_LEVEL_3
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_3
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE HIGH_LEVEL_3 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_HIGH_LEVEL_4
ON HIGH_LEVEL_4
ATTRIBUTES HIGH_LEVEL_4
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT HIGH_LEVEL_4
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE HIGH_LEVEL_4 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_TR_LEVEL_1
ON TR_LEVEL_1
ATTRIBUTES TR_LEVEL_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TR_LEVEL_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE TR_LEVEL_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_LEVELS_CONCAT_TILL_2
ON LEVELS_CONCAT_TILL_2
ATTRIBUTES LEVELS_CONCAT_TILL_2
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT LEVELS_CONCAT_TILL_2
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE LEVELS_CONCAT_TILL_2 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_ALL_LEVELS_CONCAT
ON ALL_LEVELS_CONCAT
ATTRIBUTES ALL_LEVELS_CONCAT
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ALL_LEVELS_CONCAT
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE ALL_LEVELS_CONCAT IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HEALTHCARE_CLAIMS_ALL_LEVELS_CONCAT_4
ON ALL_LEVELS_CONCAT_4
ATTRIBUTES ALL_LEVELS_CONCAT_4
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ALL_LEVELS_CONCAT_4
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HEALTHCARE_CLAIMS"
    WHERE ALL_LEVELS_CONCAT_4 IS NOT NULL
);

-- HIGH_VALUE_CLAIMS_RISK Dimension Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_HIGH_VALUE_CLAIMS_RISK_RISK_CATEGORY
ON RISK_CATEGORY
ATTRIBUTES RISK_CATEGORY
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT RISK_CATEGORY
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."HIGH_VALUE_CLAIMS_RISK"
    WHERE RISK_CATEGORY IS NOT NULL
);

-- PATIENT_COST_CATEGORIES Dimension Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PATIENT_COST_CATEGORIES_ENTITY_NO
ON ENTITY_NO
ATTRIBUTES ENTITY_NO
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENTITY_NO
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PATIENT_COST_CATEGORIES"
    WHERE ENTITY_NO IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PATIENT_COST_CATEGORIES_PROVINCE
ON PROVINCE
ATTRIBUTES PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PATIENT_COST_CATEGORIES"
    WHERE PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PATIENT_COST_CATEGORIES_AGE_GROUPS
ON AGE_GROUPS
ATTRIBUTES AGE_GROUPS
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT AGE_GROUPS
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PATIENT_COST_CATEGORIES"
    WHERE AGE_GROUPS IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PATIENT_COST_CATEGORIES_COST_CATEGORY
ON COST_CATEGORY
ATTRIBUTES COST_CATEGORY
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT COST_CATEGORY
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PATIENT_COST_CATEGORIES"
    WHERE COST_CATEGORY IS NOT NULL
);

-- PHARMACEUTICAL_CLAIMS Dimension Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ENTITY_NO
ON ENTITY_NO
ATTRIBUTES ENTITY_NO
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENTITY_NO
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ENTITY_NO IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PRODUCT_NAME
ON PRODUCT_NAME
ATTRIBUTES PRODUCT_NAME
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PRODUCT_NAME
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PRODUCT_NAME IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_NAPPI_MANUFACTURER
ON NAPPI_MANUFACTURER
ATTRIBUTES NAPPI_MANUFACTURER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT NAPPI_MANUFACTURER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE NAPPI_MANUFACTURER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_AGE_BUCKET
ON AGE_BUCKET
ATTRIBUTES AGE_BUCKET
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT AGE_BUCKET
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE AGE_BUCKET IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_AGE_GROUPS
ON AGE_GROUPS
ATTRIBUTES AGE_GROUPS
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT AGE_GROUPS
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE AGE_GROUPS IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_GENDER
ON GENDER
ATTRIBUTES GENDER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT GENDER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE GENDER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PROVINCE
ON PROVINCE
ATTRIBUTES PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_REGION_OF_RESIDENCE
ON REGION_OF_RESIDENCE
ATTRIBUTES REGION_OF_RESIDENCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REGION_OF_RESIDENCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE REGION_OF_RESIDENCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PLAN_GRP
ON PLAN_GRP
ATTRIBUTES PLAN_GRP
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PLAN_GRP
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PLAN_GRP IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PLAN_SCHEME
ON PLAN_SCHEME
ATTRIBUTES PLAN_SCHEME
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PLAN_SCHEME
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PLAN_SCHEME IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_DEG_DESCR
ON DEG_DESCR
ATTRIBUTES DEG_DESCR
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DEG_DESCR
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE DEG_DESCR IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_TREATING_DR
ON TREATING_DR
ATTRIBUTES TREATING_DR
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TREATING_DR
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE TREATING_DR IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_STRENGTH
ON STRENGTH
ATTRIBUTES STRENGTH
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STRENGTH
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE STRENGTH IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_DOSAGE_FORM
ON DOSAGE_FORM
ATTRIBUTES DOSAGE_FORM
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DOSAGE_FORM
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE DOSAGE_FORM IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ATC_DESCRIPTION
ON ATC_DESCRIPTION
ATTRIBUTES ATC_DESCRIPTION
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_DESCRIPTION
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ATC_DESCRIPTION IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_1
ON ATC_LEVEL_DESC_1
ATTRIBUTES ATC_LEVEL_DESC_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ATC_LEVEL_DESC_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_2
ON ATC_LEVEL_DESC_2
ATTRIBUTES ATC_LEVEL_DESC_2
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_2
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ATC_LEVEL_DESC_2 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_3
ON ATC_LEVEL_DESC_3
ATTRIBUTES ATC_LEVEL_DESC_3
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_3
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ATC_LEVEL_DESC_3 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_4
ON ATC_LEVEL_DESC_4
ATTRIBUTES ATC_LEVEL_DESC_4
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_4
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ATC_LEVEL_DESC_4 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_5
ON ATC_LEVEL_DESC_5
ATTRIBUTES ATC_LEVEL_DESC_5
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_5
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE ATC_LEVEL_DESC_5 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PROVIDER_TYPE
ON PROVIDER_TYPE
ATTRIBUTES PROVIDER_TYPE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_TYPE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PROVIDER_TYPE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PROVIDER_GROUP
ON PROVIDER_GROUP
ATTRIBUTES PROVIDER_GROUP
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_GROUP
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PROVIDER_GROUP IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PROVIDER
ON PROVIDER
ATTRIBUTES PROVIDER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PROVIDER IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PROVIDER_REGION
ON PROVIDER_REGION
ATTRIBUTES PROVIDER_REGION
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_REGION
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PROVIDER_REGION IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_PROVIDER_PROVINCE
ON PROVIDER_PROVINCE
ATTRIBUTES PROVIDER_PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE PROVIDER_PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_BUCKET
ON BUCKET
ATTRIBUTES BUCKET
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT BUCKET
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE BUCKET IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_PHARMACEUTICAL_CLAIMS_TR_PROCEDURE_CODE_DESCRIPTION
ON TR_PROCEDURE_CODE_DESCRIPTION
ATTRIBUTES TR_PROCEDURE_CODE_DESCRIPTION
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TR_PROCEDURE_CODE_DESCRIPTION
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."PHARMACEUTICAL_CLAIMS"
    WHERE TR_PROCEDURE_CODE_DESCRIPTION IS NOT NULL
);

-- VW_CLAIMS_SUMMARY Dimension Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_CLAIMS_SUMMARY_P_PROVINCE
ON P_PROVINCE
ATTRIBUTES P_PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT P_PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_CLAIMS_SUMMARY"
    WHERE P_PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_CLAIMS_SUMMARY_CATEGORY_DESCR
ON CATEGORY_DESCR
ATTRIBUTES CATEGORY_DESCR
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CATEGORY_DESCR
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_CLAIMS_SUMMARY"
    WHERE CATEGORY_DESCR IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_CLAIMS_SUMMARY_TR_LEVEL_1
ON TR_LEVEL_1
ATTRIBUTES TR_LEVEL_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TR_LEVEL_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_CLAIMS_SUMMARY"
    WHERE TR_LEVEL_1 IS NOT NULL
);

-- VW_PHARMA_SUMMARY Dimension Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_PHARMA_SUMMARY_PROVINCE
ON PROVINCE
ATTRIBUTES PROVINCE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVINCE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_PHARMA_SUMMARY"
    WHERE PROVINCE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_PHARMA_SUMMARY_PROVIDER_TYPE
ON PROVIDER_TYPE
ATTRIBUTES PROVIDER_TYPE
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER_TYPE
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_PHARMA_SUMMARY"
    WHERE PROVIDER_TYPE IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_PHARMA_SUMMARY_ATC_LEVEL_DESC_1
ON ATC_LEVEL_DESC_1
ATTRIBUTES ATC_LEVEL_DESC_1
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ATC_LEVEL_DESC_1
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_PHARMA_SUMMARY"
    WHERE ATC_LEVEL_DESC_1 IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_PHARMA_SUMMARY_AGE_GROUPS
ON AGE_GROUPS
ATTRIBUTES AGE_GROUPS
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT AGE_GROUPS
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_PHARMA_SUMMARY"
    WHERE AGE_GROUPS IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Quail_VW_PHARMA_SUMMARY_GENDER
ON GENDER
ATTRIBUTES GENDER
WAREHOUSE = COMPUTE_WH
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT GENDER
    FROM "QUANTIUM_HEALTHCARE_DEMO"."QUANTIUM_HEALTHCARE_DEMO"."VW_PHARMA_SUMMARY"
    WHERE GENDER IS NOT NULL
);

-- Script Complete
SHOW CORTEX SEARCH SERVICES;