name: app_environment
channels:
  - snowflake
dependencies:
  - altair=5.5.0
  - branca=0.6.0
  - h3-py=3.7.6
  - matplotlib-base=3.10.0
  - numpy=2.2.5
  - pandas=2.2.3
  - plotly=6.0.1
  - pydeck=0.9.1
  - python=3.11.*
  - scipy=1.15.3
  - snowflake-snowpark-python=
  - streamlit=